#!/bin/bash

# 🚀 Portfolio Deployment Helper Script
# This script helps deploy Harish Kumar's portfolio to various platforms

echo "🚀 Harish Kumar Portfolio - Deployment Guide"
echo "=============================================="
echo ""
echo "Your portfolio is ready for deployment! Choose your preferred option:"
echo ""
echo "🌟 RECOMMENDED DEPLOYMENT OPTIONS:"
echo ""
echo "1. 📁 Netlify (Drag & Drop - 30 seconds)"
echo "   - Easiest method"
echo "   - Free custom domain"
echo "   - Instant HTTPS"
echo "   - No account needed initially"
echo ""
echo "2. ⚡ Vercel (Professional - 2 minutes)"
echo "   - Professional hosting"
echo "   - GitHub integration"
echo "   - Custom domains"
echo "   - Great performance"
echo ""
echo "3. 🐱 GitHub Pages (Free Forever)"
echo "   - Free hosting"
echo "   - Version control"
echo "   - Professional URLs"
echo "   - Perfect for portfolios"
echo ""

read -p "Which deployment method would you like to use? (1-3): " choice

case $choice in
    1)
        echo ""
        echo "🌟 NETLIFY DEPLOYMENT (FASTEST METHOD)"
        echo "======================================"
        echo ""
        echo "✅ STEP 1: Build files are ready!"
        echo "   Location: /app/portfolio/frontend/build/"
        echo ""
        echo "✅ STEP 2: Follow these simple steps:"
        echo "   1. Open https://app.netlify.com/drop in your browser"
        echo "   2. Drag and drop the 'build' folder to the page"
        echo "   3. Wait 30 seconds for deployment"
        echo "   4. Get your live URL instantly!"
        echo ""
        echo "🎯 Expected Result:"
        echo "   Your portfolio will be live at: https://amazing-harish-portfolio.netlify.app"
        echo "   (URL will be automatically generated)"
        echo ""
        echo "💡 PRO TIP: You can later:"
        echo "   - Change the site name to harish-portfolio"
        echo "   - Add a custom domain (harishkumar.com)"
        echo "   - Enable form submissions"
        echo ""
        ;;
    2)
        echo ""
        echo "⚡ VERCEL DEPLOYMENT (PROFESSIONAL)"
        echo "=================================="
        echo ""
        echo "✅ STEP 1: Build files are ready!"
        echo "   Location: /app/portfolio/frontend/build/"
        echo ""
        echo "✅ STEP 2: Deploy to Vercel:"
        echo "   1. Go to https://vercel.com/new"
        echo "   2. Sign up with GitHub (recommended)"
        echo "   3. Click 'Browse' and upload the build folder"
        echo "   4. Click 'Deploy'"
        echo "   5. Get your professional URL!"
        echo ""
        echo "🎯 Expected Result:"
        echo "   Your portfolio will be live at: https://harish-portfolio.vercel.app"
        echo ""
        echo "💡 PRO TIP:"
        echo "   - Connect your GitHub for automatic updates"
        echo "   - Add custom domain easily"
        echo "   - Great for professional use"
        echo ""
        ;;
    3)
        echo ""
        echo "🐱 GITHUB PAGES DEPLOYMENT"
        echo "=========================="
        echo ""
        echo "✅ STEP 1: Create GitHub Repository"
        echo "   1. Go to https://github.com/new"
        echo "   2. Repository name: 'harish-portfolio'"
        echo "   3. Make it public"
        echo "   4. Create repository"
        echo ""
        echo "✅ STEP 2: Upload your files"
        echo "   1. Upload all contents from: /app/portfolio/frontend/build/"
        echo "   2. Drag and drop files to GitHub"
        echo "   3. Commit changes"
        echo ""
        echo "✅ STEP 3: Enable GitHub Pages"
        echo "   1. Go to repository Settings"
        echo "   2. Scroll to 'Pages' section"
        echo "   3. Source: Deploy from a branch"
        echo "   4. Branch: main"
        echo "   5. Save"
        echo ""
        echo "🎯 Expected Result:"
        echo "   Your portfolio will be live at: https://Harry044.github.io/harish-portfolio"
        echo ""
        echo "💡 PRO TIP:"
        echo "   - Free forever"
        echo "   - Professional GitHub URL"
        echo "   - Version control included"
        echo ""
        ;;
    *)
        echo ""
        echo "❌ Invalid choice. Please run the script again and choose 1, 2, or 3."
        exit 1
        ;;
esac

echo ""
echo "📋 QUICK DEPLOYMENT CHECKLIST:"
echo "==============================="
echo "✅ Portfolio build completed"
echo "✅ All sections updated with your real information"
echo "✅ Mobile responsive design verified"
echo "✅ Contact form functional"
echo "✅ LinkedIn and GitHub links working"
echo "✅ Professional photo included"
echo "✅ Ready for recruiter/employer viewing"
echo ""
echo "🎉 After deployment, your portfolio will showcase:"
echo "   📊 Your Data Science & AI learning journey"
echo "   🛠️ Real projects (Power Monitoring System)"
echo "   🎓 Accurate education details"
echo "   🏆 Professional certifications"
echo "   💼 Complete skill set"
echo ""
echo "🌍 Share your live portfolio URL with:"
echo "   • Potential employers"
echo "   • Professional networks"
echo "   • Social media profiles"
echo "   • Resume/CV applications"
echo ""
echo "Good luck with your deployment! 🚀"